# Generated by Django 6.0.2 on 2026-02-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_date',
        ),
    ]
