# Generated by Django 6.0.2 on 2026-02-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('washing', 'Washing'), ('drying', 'Drying'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered')], default='received', max_length=20),
        ),
    ]
